name: DevContainer Template CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-devcontainer-template:
    name: Full DevContainer Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Create .env for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="dummy-openai"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="dummy-add-key"' >> devcontainers/goodmem-dev/.env

      - name: Start container
        run: |
          devcontainer up --workspace-folder devcontainers/goodmem-dev --skip-post-create

      - name: ✅ Test Python package installation
        run: |
          devcontainer exec --workspace-folder devcontainers/goodmem-dev bash -c '
            python3 -c "
            import sys
            print(\"Python version:\", sys.version)
            import goodmem_client, openai, requests, psycopg2
            from dotenv import load_dotenv
            print(\"✅ All Python dependencies imported successfully.\")"
          '

      - name: ✅ Test multi-language runtimes
        run: |
          devcontainer exec --workspace-folder devcontainers/goodmem-dev bash -c '
            echo "🧪 Testing Java:"
            java -version && javac -version

            echo "🧪 Testing .NET:"
            dotnet --version

            echo "🧪 Testing Go:"
            go version

            echo "🧪 Testing Node.js:"
            node --version && npm --version && pnpm --version

            echo "✅ All runtimes available"
          '

      - name: ✅ Run tests/test.py
        run: |
          devcontainer exec --workspace-folder devcontainers/goodmem-dev bash -c '
            cd /workspaces/goodmem-container && python3 tests/test.py
          '

      - name: ✅ Test GoodMem API imports
        run: |
          devcontainer exec --workspace-folder devcontainers/goodmem-dev bash -c '
            python3 -c "
            from goodmem_client.api import APIKeysApi, SpacesApi, MemoriesApi
            from goodmem_client.configuration import Configuration
            from goodmem_client.api_client import ApiClient
            print(\"✅ GoodMem API imports successful\")
            from openai import OpenAI
            print(\"✅ OpenAI import successful\")
            "
          '

      - name: ✅ Test environment configuration
        run: |
          devcontainer exec --workspace-folder devcontainers/goodmem-dev bash -c '
            python3 -c "
            import os
            assert os.getenv(\"OPENAI_API_KEY\"), \"❌ OPENAI_API_KEY not set\"
            assert os.getenv(\"ADD_API_KEY\"), \"❌ ADD_API_KEY not set\"
            print(\"✅ Environment variables loaded successfully\")
            "
          '

      - name: ✅ Validate template structure
        run: |
          echo "🧪 Validating template structure..."
          python3 -m json.tool devcontainers/goodmem-dev/devcontainer.json > /dev/null
          echo "✅ devcontainer.json is valid JSON"

          REQUIRED_FILES=(
            "devcontainers/goodmem-dev/devcontainer.json"
            "devcontainers/goodmem-dev/Dockerfile"
            "devcontainers/goodmem-dev/.env"
            "setup.sh"
            ".gitignore"
          )

          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing required file: $file"
              exit 1
            else
              echo "✅ Found: $file"
            fi
          done

      - name: ✅ Check setup.sh is executable
        run: |
          chmod +x setup.sh
          if [ -x setup.sh ]; then
            echo "✅ setup.sh is executable"
          else
            echo "❌ setup.sh is not executable"
            exit 1
          fi
