name: DevContainer Template CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Full DevContainer Test Suite
    runs-on: ubuntu-latest
    env:
      WORKSPACE: test-workspace

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up test workspace
        run: |
          mkdir -p $WORKSPACE/.devcontainer
          cp src/goodmem-dev/.devcontainer.json $WORKSPACE/.devcontainer/devcontainer.json
          cp build/Dockerfile $WORKSPACE/.devcontainer/
          cp build/setup.sh $WORKSPACE/
          echo 'OPENAI_API_KEY="test-key"' > $WORKSPACE/.devcontainer/.env
          echo 'ADD_API_KEY="test-key"' >> $WORKSPACE/.devcontainer/.env

      - name: Validate devcontainer.json
        run: |
          python3 -m json.tool $WORKSPACE/.devcontainer/devcontainer.json

      - name: Build DevContainer
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never

      - name: Run Package Import Test
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 -c "
            import goodmem_client, openai, requests, psycopg2
            from dotenv import load_dotenv
            print('✅ Python packages verified')
            "

      - name: Run Language Runtime Test
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 --version
            java -version
            dotnet --version
            go version
            node --version
            npm --version
            pnpm --version
            echo "✅ All language runtimes installed"

      - name: Run GoodMem API Import Test
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 -c "
            from goodmem_client.api import APIKeysApi
            from goodmem_client.configuration import Configuration
            from goodmem_client.api_client import ApiClient
            print('✅ GoodMem API modules imported')
            "

      - name: Verify .env configuration
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 -c "
            from dotenv import load_dotenv
            import os
            load_dotenv(dotenv_path='.devcontainer/.env')
            assert 'OPENAI_API_KEY' in os.environ
            assert 'ADD_API_KEY' in os.environ
            print('✅ .env variables present')
            "

  publish:
    name: Build and Publish Docker Image
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: |
            ghcr.io/mariamahmad8/goodmem-container:${{ env.VERSION }}
            ghcr.io/mariamahmad8/goodmem-container:latest
