name: DevContainer Template CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-package-installation:
    name: Test Package Installation
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> devcontainers/goodmem-dev/.env

      - name: Run Python dependency checks
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/goodmem-dev/.
          push: never
          runCmd: |
            python3 -c "
            import sys
            print('Python version:', sys.version)
            import goodmem_client, openai, requests, psycopg2
            from dotenv import load_dotenv
            print('All dependencies imported successfully')
            "

  test-language-installations:
    name: Test Multi-Language Installations
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> devcontainers/goodmem-dev/.env

      - name: Run language version checks
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/goodmem-dev/.
          push: never
          runCmd: |
            python3 --version
            java -version
            dotnet --version
            go version
            node --version
            npm --version
            pnpm --version
            echo "All language runtimes installed successfully"

  run-tests:
    name: Run Custom Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> devcontainers/goodmem-dev/.env

      - name: Run tests/test.py
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/goodmem-dev/.
          push: never
          runCmd: |
            cd /workspaces/goodmem-container
            python3 tests/test.py

  test-api-imports:
    name: Test API Imports
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> devcontainers/goodmem-dev/.env

      - name: Import API clients
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/goodmem-dev/.
          push: never
          runCmd: |
            python3 -c "
            from goodmem_client.api import APIKeysApi, SpacesApi, MemoriesApi
            from goodmem_client.configuration import Configuration
            from goodmem_client.api_client import ApiClient
            from openai import OpenAI
            print('API clients imported successfully')
            "

  test-configuration:
    name: Test Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          mkdir -p devcontainers/goodmem-dev
          echo 'OPENAI_API_KEY="dummy-value"' > devcontainers/goodmem-dev/.env
          echo 'ADD_API_KEY="dummy-value"' >> devcontainers/goodmem-dev/.env

      - name: Verify env vars exist
        uses: devcontainers/ci@v0.3
        with:
          subFolder: devcontainers/goodmem-dev/.
          push: never
          runCmd: |
            python3 -c "
            import os
            assert os.getenv('OPENAI_API_KEY'), 'Missing OPENAI_API_KEY'
            assert os.getenv('ADD_API_KEY'), 'Missing ADD_API_KEY'
            print('Env vars set correctly')
            "

  validate-template:
    name: Validate Template Files
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate devcontainer.json syntax
        run: python3 -m json.tool devcontainers/goodmem-dev/devcontainer.json > /dev/null

      - name: Check required files
        run: |
          required=(
            "devcontainers/goodmem-dev/devcontainer.json"
            "devcontainers/goodmem-dev/Dockerfile"
            "devcontainers/goodmem-dev/.env"
            "setup.sh"
            ".gitignore"
          )
          for f in "${required[@]}"; do
            if [ ! -f "$f" ]; then
              echo "❌ Missing $f"
              exit 1
            else
              echo "✅ Found $f"
            fi
          done

      - name: Check setup.sh is executable
        run: |
          chmod +x setup.sh
          if [ -x setup.sh ]; then
            echo "✅ setup.sh is executable"
          else
            echo "❌ setup.sh is not executable"
            exit 1
          fi
