name: DevContainer Template CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-devcontainer-build:
    name: Test DevContainer Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup test workspace from template
        run: |
          # Create a test workspace that uses our template
          mkdir -p test-workspace/.devcontainer
          cp src/goodmem-dev/.devcontainer.json test-workspace/.devcontainer/devcontainer.json
          cp build/Dockerfile test-workspace/.devcontainer/
          cp build/setup.sh test-workspace/
          
          # Create test .env file
          echo 'OPENAI_API_KEY="test-key"' > test-workspace/.devcontainer/.env
          echo 'ADD_API_KEY="test-key"' >> test-workspace/.devcontainer/.env

      - name: Test devcontainer build
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: test-workspace
          push: never
          runCmd: |
            echo "DevContainer built successfully"
            python3 --version
            echo "Python is available"

  test-package-installation:
    name: Test Package Installation
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup test workspace from template
        run: |
          mkdir -p test-workspace/.devcontainer
          cp src/goodmem-dev/.devcontainer.json test-workspace/.devcontainer/devcontainer.json
          cp build/Dockerfile test-workspace/.devcontainer/
          cp build/setup.sh test-workspace/
          echo 'OPENAI_API_KEY="test-key"' > test-workspace/.devcontainer/.env
          echo 'ADD_API_KEY="test-key"' >> test-workspace/.devcontainer/.env

      - name: Test all packages are installed
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: test-workspace
          push: never
          runCmd: |
            python3 -c "
            import sys
            print('Python version:', sys.version)
            
            # Test GoodMem client
            try:
                import goodmem_client
                print('goodmem_client imported successfully')
            except ImportError as e:
                print('goodmem_client import failed:', e)
                exit(1)
            
            # Test OpenAI
            try:
                import openai
                print('openai imported successfully')
            except ImportError as e:
                print('openai import failed:', e)
                exit(1)
            
            # Test other dependencies
            try:
                import requests
                import psycopg2
                from dotenv import load_dotenv
                print('All dependencies imported successfully')
            except ImportError as e:
                print('Dependency import failed:', e)
                exit(1)
            "

  test-language-installations:
    name: Test Multi-Language Installations
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo '# GoodMem Development Environment Configuration' > src/goodmem-dev/.env
          echo '# Replace these with your actual API keys' >> src/goodmem-dev/.env
          echo '' >> src/goodmem-dev/.env
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' >> src/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> src/goodmem-dev/.env

      - name: Test all language runtimes
        uses: devcontainers/ci@v0.3
        with:
          configFile: src/goodmem-dev/.devcontainer.json
          push: never
          runCmd: |
            # Test Python
            python3 --version
            echo "Python installation: OK"
            
            # Test Java
            java -version
            javac -version
            echo "Java installation: OK"
            
            # Test .NET
            dotnet --version
            echo ".NET installation: OK"
            
            # Test Go
            go version
            echo "Go installation: OK"
            
            # Test Node.js
            node --version
            npm --version
            pnpm --version
            echo "Node.js installation: OK"
            
            echo "All language runtimes installed successfully"

  run-tests:
    name: Run Custom Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo '# GoodMem Development Environment Configuration' > src/goodmem-dev/.env
          echo '# Replace these with your actual API keys' >> src/goodmem-dev/.env
          echo '' >> src/goodmem-dev/.env
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' >> src/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> src/goodmem-dev/.env

      - name: Run test.py
        uses: devcontainers/ci@v0.3
        with:
          configFile: src/goodmem-dev/.devcontainer.json
          push: never
          runCmd: |
            cd /workspaces/goodmem-container
            python3 tests/test.py

  test-api-imports:
    name: Test API Imports
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo '# GoodMem Development Environment Configuration' > src/goodmem-dev/.env
          echo '# Replace these with your actual API keys' >> src/goodmem-dev/.env
          echo '' >> src/goodmem-dev/.env
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' >> src/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> src/goodmem-dev/.env

      - name: Test GoodMem API imports
        uses: devcontainers/ci@v0.3
        with:
          configFile: src/goodmem-dev/.devcontainer.json
          push: never
          runCmd: |
            python3 -c "
            try:
                from goodmem_client.api import APIKeysApi, SpacesApi, MemoriesApi
                from goodmem_client.configuration import Configuration
                from goodmem_client.api_client import ApiClient
                print('GoodMem API imports successful')
            except ImportError as e:
                print('GoodMem API import failed:', e)
                exit(1)
            
            try:
                from openai import OpenAI
                print('OpenAI client import successful')
            except ImportError as e:
                print('OpenAI client import failed:', e)
                exit(1)
            "

  test-configuration:
    name: Test Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo '# GoodMem Development Environment Configuration' > src/goodmem-dev/.env
          echo '# Replace these with your actual API keys' >> src/goodmem-dev/.env
          echo '' >> src/goodmem-dev/.env
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' >> src/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> src/goodmem-dev/.env

      - name: Test environment configuration
        uses: devcontainers/ci@v0.3
        with:
          configFile: src/goodmem-dev/.devcontainer.json
          push: never
          runCmd: |
            python3 -c "
            from dotenv import load_dotenv
            import os
            
            # Load environment variables
            load_dotenv(dotenv_path='src/goodmem-dev/.env')
            
            # Check if template variables exist
            openai_key = os.getenv('OPENAI_API_KEY')
            goodmem_key = os.getenv('ADD_API_KEY')
            
            if openai_key and 'your-openai-api-key-here' in openai_key:
                print('OpenAI key template found')
            else:
                print('OpenAI key template not found')
                exit(1)
                
            if goodmem_key and 'your-goodmem-api-key-here' in goodmem_key:
                print('GoodMem key template found')
            else:
                print('GoodMem key template not found')
                exit(1)
                
            print('Environment configuration is correct')
            "

  validate-template:
    name: Validate Template Structure
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo '# GoodMem Development Environment Configuration' > src/goodmem-dev/.env
          echo '# Replace these with your actual API keys' >> src/goodmem-dev/.env
          echo '' >> src/goodmem-dev/.env
          echo 'OPENAI_API_KEY="your-openai-api-key-here"' >> src/goodmem-dev/.env
          echo 'ADD_API_KEY="your-goodmem-api-key-here"' >> src/goodmem-dev/.env

      - name: Validate devcontainer.json
        run: |
          # Check if devcontainer.json is valid JSON
          python3 -m json.tool src/goodmem-dev/.devcontainer.json > /dev/null
          echo "devcontainer.json is valid JSON"

      - name: Check required files
        run: |
          files=(
            "src/goodmem-dev/.devcontainer.json"
            "build/Dockerfile" 
            "src/goodmem-dev/.env"
            "build/setup.sh"
            ".gitignore"
          )
          
          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Missing required file: $file"
              exit 1
            else
              echo "Found: $file"
            fi
          done

      - name: Check setup script is executable
        run: |
          if [ -x "build/setup.sh" ]; then
            echo "build/setup.sh is executable"
          else
            echo "build/setup.sh is not executable"
            exit 1
          fi


  publish-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: build
          file: build/Dockerfile
          push: true
          tags: ghcr.io/mariamahmad8/goodmem-container:latest
