name: Build and Publish DevContainer

on:
  push:
    branches: [main]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and push the devcontainer image
        run: |
          docker login --username mariamahmad8 --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build .devcontainer --tag ghcr.io/mariamahmad8/goodmem-devcontainer:latest
          docker push ghcr.io/mariamahmad8/goodmem-devcontainer:latest