name: Release DevContainer Template

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    name: Test DevContainer Template
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug - Show file structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Root files ==="
          ls -la
          echo "=== build/ directory ==="
          ls -la build/
          echo "=== src/goodmem-dev/ directory ==="
          ls -la src/goodmem-dev/

      - name: Create .env for testing
        run: |
          echo 'OPENAI_API_KEY="test-key"' > src/goodmem-dev/.env
          echo 'ADD_API_KEY="test-key"' >> src/goodmem-dev/.env

      - name: Test DevContainer Build and Language Runtimes
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/goodmem-dev
          configFile: src/goodmem-dev/.devcontainer.json
          push: never
          runCmd: |
            echo "=== Testing Language Runtimes ==="
            python3 --version
            java -version
            dotnet --version
            go version
            node --version
            pnpm --version
            echo "✅ All language runtimes working"
            
            echo "=== Testing Package Imports ==="
            python3 -c "
            import goodmem_client, openai, requests, psycopg2
            from goodmem_client.api import APIKeysApi
            from dotenv import load_dotenv
            print('✅ All packages imported successfully')
            "

  release:
    name: Build and Release Docker Image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: |
            ghcr.io/mariamahmad8/goodmem-container:${{ steps.version.outputs.VERSION }}
            ghcr.io/mariamahmad8/goodmem-container:latest