name: Release DevContainer Template

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    name: Test DevContainer Template
    runs-on: ubuntu-latest
    env:
      WORKSPACE: test-workspace

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug - Show file structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Root files ==="
          ls -la
          echo "=== build/ directory ==="
          ls -la build/
          echo "=== src/goodmem-dev/ directory ==="
          ls -la src/goodmem-dev/

      - name: Set up test workspace
        run: |
          mkdir -p $WORKSPACE/.devcontainer
          cp src/goodmem-dev/.devcontainer.json $WORKSPACE/.devcontainer/devcontainer.json
          cp build/Dockerfile $WORKSPACE/.devcontainer/
          cp build/setup.sh $WORKSPACE/
          echo 'OPENAI_API_KEY="test-key"' > $WORKSPACE/.env
          echo 'ADD_API_KEY="test-key"' >> $WORKSPACE/.env

      - name: Validate devcontainer.json
        run: |
          python3 -m json.tool $WORKSPACE/.devcontainer/devcontainer.json

      - name: Test DevContainer Build
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 --version
            java -version
            dotnet --version
            go version
            node --version
            echo "✅ All language runtimes working"

      - name: Test Package Imports
        uses: devcontainers/ci@v0.3
        with:
          workspaceFolder: ${{ env.WORKSPACE }}
          push: never
          runCmd: |
            python3 -c "
            import goodmem_client, openai, requests, psycopg2
            from goodmem_client.api import APIKeysApi
            print('✅ All packages imported successfully')
            "

  release:
    name: Build and Release Docker Image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: |
            ghcr.io/mariamahmad8/goodmem-container:${{ steps.version.outputs.VERSION }}
            ghcr.io/mariamahmad8/goodmem-container:latest