name: Release DevContainer Template

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    name: Test DevContainer Template
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Debug - Show file structure
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Root files ==="
          ls -la
          echo "=== src/ directory ==="
          ls -la src/
          echo "=== src/goodmem-devcontainer/.devcontainer/ directory ==="
          ls -la src/goodmem-devcontainer/.devcontainer/

      - name: Create .env for testing
        run: |
          echo 'OPENAI_API_KEY="test-key"' > .env
          echo 'ADD_API_KEY="test-key"' >> .env

      - name: Test DevContainer Build and Basic Runtimes
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/goodmem-devcontainer
          configFile: src/goodmem-devcontainer/.devcontainer/devcontainer.json
          push: never
          runCmd: |
            echo "=== Testing Core Runtimes ==="
            python3 --version
            java -version
            dotnet --version
            go version
            node --version
            echo "Core runtimes available"

      - name: Test Python GoodMem SDK Integration
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/goodmem-devcontainer
          configFile: src/goodmem-devcontainer/.devcontainer/devcontainer.json
          push: never
          runCmd: |
            echo "=== Testing Python Package Imports ==="
            python3 -c "
            try:
                import goodmem_client
                from goodmem_client.api import APIKeysApi, SpacesApi, MemoriesApi
                from goodmem_client.configuration import Configuration
                from goodmem_client.api_client import ApiClient
                import openai
                from openai import OpenAI
                import requests
                import psycopg2
                from dotenv import load_dotenv
                import os
                print('All Python packages imported successfully')
            except ImportError as e:
                print(f'Import failed: {e}')
                exit(1)
            "

      - name: Run Comprehensive Python Test Suite
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/goodmem-devcontainer
          configFile: src/goodmem-devcontainer/.devcontainer/devcontainer.json
          push: never
          runCmd: |
            echo "=== Running Full Python Test Suite ==="
            cd /workspaces/devcontainer
            python3 tests/test.py
            echo "Python GoodMem integration tests completed"

  publish-template:
    name: Publish DevContainer Template
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish DevContainer Template
        uses: devcontainers/action@v1
        with:
          publish-templates: true
          base-path-to-templates: ./src
          generate-docs: true

